version: '3'
services:
  jekyll:
    image: jekyll/jekyll:3.8
    environment:
      - JEKYLL_ENV=development
    command: >
      sh -c "
      bundle install &&
      bundle exec jekyll serve --trace --watch --incremental --host 0.0.0.0"
    ports:
      - 4000:4000
    volumes: 
      - .:/srv/jekyll:cached
      - ./vendor/bundle:/usr/local/bundle:cached